Repository FinalForEach/Cosmic-Reach-Localization, pull requests merged in 2024-09, with the labels that each got.

#42 Create nl_be.json
  assets/lang/nl_be.json
Labels: credits needed before merge!

#122 Added CJK character font
  CREDITS.txt
  assets/lang/textures/cosmic-reach-font-cjk.png
Labels: special font rendering required

#63 Created Japanese Translations
  CREDITS.txt
  assets/lang/ja-jp.json
Labels: delayed, special font rendering required

#60 Added Chinese simplified language file and translated more for Pirate Speak
  CREDITS.txt
  assets/base/lang/en_pirate.json
  assets/base/lang/zh_CN.json
Labels: delayed, special font rendering required
